source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target "kibatina" do
#    pod 'AFNetworking', '~> 2.5'
#    pod 'SDWebImage', '3.7.3'
#     pod 'SDWebImage', '~>3.8'
#    pod 'MWPhotoBrowser', '2.1.1'
#    pod 'MWPhotoBrowser'
#    pod 'XHRealTimeBlur'
#    pod 'pop'
#    pod 'Qiniu'
     pod 'IQKeyboardManager'
#    pod 'FDFullscreenPopGesture', '1.1'
#    pod 'BaiduMapKit' #百度地图SDK
#    pod "GCDWebServer/WebUploader", "~> 3.0"
#    pod 'YTKNetwork'
#    pod 'TCBlobDownload'
     pod 'MBProgressHUD', '~> 0.9.2'
#    pod 'MJRefresh'
#    pod 'YYText'
#    pod 'UMengSocial', '~> 5.0'
#    pod 'UMengSocialCOM', '~> 5.2.1'
#    pod 'SDCycleScrollView','~> 1.75'
end
